import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DataContext from "@/store/DataContext";
import App from "next/app";
import { Providers } from "./Providers";
import AxiosInterceptorProvider from "@/utils/axiosInterceptorProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <DataContext>
          <AxiosInterceptorProvider>
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased pt-20`}
            >
              {children}
            </body>
          </AxiosInterceptorProvider>
        </DataContext>
      </Providers>
    </html>
  );
}
