export const mapCategoriesToSelect = (categories: any[]) =>
  categories.map((cat) => ({ label: cat.name, value: cat._id }));

// ====================================================
// ==================== SIZE GROUPS ====================
// ====================================================

// EU Shoe Sizes
export const euShoesSizes = [
  34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
].map((n) => ({ label: `${n}`, value: n }));

// US Shoe Sizes (Men/Women combined common range)
export const usShoesSizes = [4, 5, 6, 7, 8, 9, 10, 11, 12, 13].map((n) => ({
  label: `${n}`,
  value: n,
}));

// UK Shoe Sizes
export const ukShoesSizes = [3, 4, 5, 6, 7, 8, 9, 10, 11, 12].map((n) => ({
  label: `${n}`,
  value: n,
}));

// Clothing Alpha Sizes
export const alphaClothingSizes = [
  "XS",
  "S",
  "M",
  "L",
  "XL",
  "2XL",
  "3XL",
  "4XL",
  "5XL",
  "6XL",
  "7XL",
].map((s) => ({ label: s, value: s }));

// Trouser / Jeans Sizes
export const trouserSizes = [26, 28, 30, 32, 34, 36, 38, 40, 42].map((n) => ({
  label: `${n}`,
  value: n,
}));

// Kids Clothing Sizes
export const kidsClothingSizes = [
  "0-3M",
  "3-6M",
  "6-9M",
  "9-12M",
  "1-2Y",
  "2-3Y",
  "3-4Y",
  "4-5Y",
  "6-7Y",
  "8-9Y",
  "10-11Y",
  "12-13Y",
].map((s) => ({ label: s, value: s }));

// Cap Sizes
export const capSizes = [
  "S",
  "M",
  "L",
  "XL",
  "54cm",
  "55cm",
  "56cm",
  "57cm",
  "58cm",
  "59cm",
  "60cm",
].map((s) => ({ label: s, value: s }));

// Watch Strap Sizes
export const watchSizes = ["14mm", "16mm", "18mm", "20mm", "22mm", "24mm"].map(
  (s) => ({ label: s, value: s })
);

// Necklace Lengths
export const necklaceSizes = [
  "14in",
  "16in",
  "18in",
  "20in",
  "22in",
  "24in",
  "26in",
].map((s) => ({ label: s, value: s }));

// Shirt / Top Numeric Sizes
export const shirtNumberSizes = [34, 36, 38, 40, 42, 44, 46].map((n) => ({
  label: `${n}`,
  value: n,
}));

export const bagSizes = [
  { label: "Small (25 x 15 x 10 cm)", value: "S-25x15x10" },
  { label: "Medium (30 x 20 x 15 cm)", value: "M-30x20x15" },
  { label: "Large (40 x 30 x 20 cm)", value: "L-40x30x20" },
];

// ====================================================
// ========== SIZE TYPE SELECT (MASTER SELECT) =========
// ====================================================
export const sizeTypeSelect = [
  { label: "EU Shoe Sizes", value: "euShoesSizes" },
  { label: "US Shoe Sizes", value: "usShoesSizes" },
  { label: "UK Shoe Sizes", value: "ukShoesSizes" },
  { label: "Clothing (XS - 7XL)", value: "alphaClothingSizes" },
  { label: "Trousers/Jeans Numeric Sizes", value: "trouserSizes" },
  { label: "Kids Clothing Sizes", value: "kidsClothingSizes" },
  { label: "Cap Sizes", value: "capSizes" },
  { label: "Watch Strap Sizes", value: "watchSizes" },
  { label: "Necklace Lengths", value: "necklaceSizes" },
  { label: "Shirt/Top Numbered Sizes", value: "shirtNumberSizes" },
  { label: "Bag Sizes", value: "bagSizes" },
];

export const countrySelect = [
  // { label: "Afghanistan", value: "Afghanistan" },
  // { label: "Albania", value: "Albania" },
  // { label: "Algeria", value: "Algeria" },
  // { label: "Andorra", value: "Andorra" },
  // { label: "Angola", value: "Angola" },
  // { label: "Antigua and Barbuda", value: "Antigua and Barbuda" },
  // { label: "Argentina", value: "Argentina" },
  // { label: "Armenia", value: "Armenia" },
  // { label: "Australia", value: "Australia" },
  // { label: "Austria", value: "Austria" },
  // { label: "Azerbaijan", value: "Azerbaijan" },
  // { label: "Bahamas", value: "Bahamas" },
  // { label: "Bahrain", value: "Bahrain" },
  // { label: "Bangladesh", value: "Bangladesh" },
  // { label: "Barbados", value: "Barbados" },
  // { label: "Belarus", value: "Belarus" },
  // { label: "Belgium", value: "Belgium" },
  // { label: "Belize", value: "Belize" },
  // { label: "Benin", value: "Benin" },
  // { label: "Bhutan", value: "Bhutan" },
  // { label: "Bolivia", value: "Bolivia" },
  // { label: "Bosnia and Herzegovina", value: "Bosnia and Herzegovina" },
  // { label: "Botswana", value: "Botswana" },
  // { label: "Brazil", value: "Brazil" },
  // { label: "Brunei", value: "Brunei" },
  // { label: "Bulgaria", value: "Bulgaria" },
  // { label: "Burkina Faso", value: "Burkina Faso" },
  // { label: "Burundi", value: "Burundi" },
  // { label: "Cabo Verde", value: "Cabo Verde" },
  // { label: "Cambodia", value: "Cambodia" },
  // { label: "Cameroon", value: "Cameroon" },
  // { label: "Canada", value: "Canada" },
  // { label: "Central African Republic", value: "Central African Republic" },
  // { label: "Chad", value: "Chad" },
  // { label: "Chile", value: "Chile" },
  // { label: "China", value: "China" },
  // { label: "Colombia", value: "Colombia" },
  // { label: "Comoros", value: "Comoros" },
  // { label: "Congo (Congo-Brazzaville)", value: "Congo (Congo-Brazzaville)" },
  // { label: "Costa Rica", value: "Costa Rica" },
  // { label: "Croatia", value: "Croatia" },
  // { label: "Cuba", value: "Cuba" },
  // { label: "Cyprus", value: "Cyprus" },
  // { label: "Czechia (Czech Republic)", value: "Czechia (Czech Republic)" },
  // {
  //   label: "Democratic Republic of the Congo",
  //   value: "Democratic Republic of the Congo",
  // },
  // { label: "Denmark", value: "Denmark" },
  // { label: "Djibouti", value: "Djibouti" },
  // { label: "Dominica", value: "Dominica" },
  // { label: "Dominican Republic", value: "Dominican Republic" },
  // { label: "Ecuador", value: "Ecuador" },
  // { label: "Egypt", value: "Egypt" },
  // { label: "El Salvador", value: "El Salvador" },
  // { label: "Equatorial Guinea", value: "Equatorial Guinea" },
  // { label: "Eritrea", value: "Eritrea" },
  // { label: "Estonia", value: "Estonia" },
  // { label: 'Eswatini (fmr. "Swaziland")', value: "Eswatini" },
  // { label: "Ethiopia", value: "Ethiopia" },
  // { label: "Fiji", value: "Fiji" },
  // { label: "Finland", value: "Finland" },
  // { label: "France", value: "France" },
  // { label: "Gabon", value: "Gabon" },
  // { label: "Gambia", value: "Gambia" },
  // { label: "Georgia", value: "Georgia" },
  // { label: "Germany", value: "Germany" },
  // { label: "Ghana", value: "Ghana" },
  // { label: "Greece", value: "Greece" },
  // { label: "Grenada", value: "Grenada" },
  // { label: "Guatemala", value: "Guatemala" },
  // { label: "Guinea", value: "Guinea" },
  // { label: "Guinea-Bissau", value: "Guinea-Bissau" },
  // { label: "Guyana", value: "Guyana" },
  // { label: "Haiti", value: "Haiti" },
  // { label: "Holy See", value: "Holy See" },
  // { label: "Honduras", value: "Honduras" },
  // { label: "Hungary", value: "Hungary" },
  // { label: "Iceland", value: "Iceland" },
  // { label: "India", value: "India" },
  // { label: "Indonesia", value: "Indonesia" },
  // { label: "Iran", value: "Iran" },
  // { label: "Iraq", value: "Iraq" },
  // { label: "Ireland", value: "Ireland" },
  // { label: "Israel", value: "Israel" },
  // { label: "Italy", value: "Italy" },
  // { label: "Jamaica", value: "Jamaica" },
  // { label: "Japan", value: "Japan" },
  // { label: "Jordan", value: "Jordan" },
  // { label: "Kazakhstan", value: "Kazakhstan" },
  // { label: "Kenya", value: "Kenya" },
  // { label: "Kiribati", value: "Kiribati" },
  // { label: "Kuwait", value: "Kuwait" },
  // { label: "Kyrgyzstan", value: "Kyrgyzstan" },
  // { label: "Laos", value: "Laos" },
  // { label: "Latvia", value: "Latvia" },
  // { label: "Lebanon", value: "Lebanon" },
  // { label: "Lesotho", value: "Lesotho" },
  // { label: "Liberia", value: "Liberia" },
  // { label: "Libya", value: "Libya" },
  // { label: "Liechtenstein", value: "Liechtenstein" },
  // { label: "Lithuania", value: "Lithuania" },
  // { label: "Luxembourg", value: "Luxembourg" },
  // { label: "Madagascar", value: "Madagascar" },
  // { label: "Malawi", value: "Malawi" },
  // { label: "Malaysia", value: "Malaysia" },
  // { label: "Maldives", value: "Maldives" },
  // { label: "Mali", value: "Mali" },
  // { label: "Malta", value: "Malta" },
  // { label: "Marshall Islands", value: "Marshall Islands" },
  // { label: "Mauritania", value: "Mauritania" },
  // { label: "Mauritius", value: "Mauritius" },
  // { label: "Mexico", value: "Mexico" },
  // { label: "Micronesia", value: "Micronesia" },
  // { label: "Moldova", value: "Moldova" },
  // { label: "Monaco", value: "Monaco" },
  // { label: "Mongolia", value: "Mongolia" },
  // { label: "Montenegro", value: "Montenegro" },
  // { label: "Morocco", value: "Morocco" },
  // { label: "Mozambique", value: "Mozambique" },
  // { label: "Myanmar (Burma)", value: "Myanmar" },
  // { label: "Namibia", value: "Namibia" },
  // { label: "Nauru", value: "Nauru" },
  // { label: "Nepal", value: "Nepal" },
  // { label: "Netherlands", value: "Netherlands" },
  // { label: "New Zealand", value: "New Zealand" },
  // { label: "Nicaragua", value: "Nicaragua" },
  // { label: "Niger", value: "Niger" },
  { label: "Nigeria", value: "Nigeria" },
  // { label: "North Korea", value: "North Korea" },
  // { label: "North Macedonia", value: "North Macedonia" },
  // { label: "Norway", value: "Norway" },
  // { label: "Oman", value: "Oman" },
  // { label: "Pakistan", value: "Pakistan" },
  // { label: "Palau", value: "Palau" },
  // { label: "Panama", value: "Panama" },
  // { label: "Papua New Guinea", value: "Papua New Guinea" },
  // { label: "Paraguay", value: "Paraguay" },
  // { label: "Peru", value: "Peru" },
  // { label: "Philippines", value: "Philippines" },
  // { label: "Poland", value: "Poland" },
  // { label: "Portugal", value: "Portugal" },
  // { label: "Qatar", value: "Qatar" },
  // { label: "Romania", value: "Romania" },
  // { label: "Russia", value: "Russia" },
  // { label: "Rwanda", value: "Rwanda" },
  // { label: "Saint Kitts and Nevis", value: "Saint Kitts and Nevis" },
  // { label: "Saint Lucia", value: "Saint Lucia" },
  // {
  //   label: "Saint Vincent and the Grenadines",
  //   value: "Saint Vincent and the Grenadines",
  // },
  // { label: "Samoa", value: "Samoa" },
  // { label: "San Marino", value: "San Marino" },
  // { label: "Sao Tome and Principe", value: "Sao Tome and Principe" },
  // { label: "Saudi Arabia", value: "Saudi Arabia" },
  // { label: "Senegal", value: "Senegal" },
  // { label: "Serbia", value: "Serbia" },
  // { label: "Seychelles", value: "Seychelles" },
  // { label: "Sierra Leone", value: "Sierra Leone" },
  // { label: "Singapore", value: "Singapore" },
  // { label: "Slovakia", value: "Slovakia" },
  // { label: "Slovenia", value: "Slovenia" },
  // { label: "Solomon Islands", value: "Solomon Islands" },
  // { label: "Somalia", value: "Somalia" },
  // { label: "South Africa", value: "South Africa" },
  // { label: "South Korea", value: "South Korea" },
  // { label: "South Sudan", value: "South Sudan" },
  // { label: "Spain", value: "Spain" },
  // { label: "Sri Lanka", value: "Sri Lanka" },
  // { label: "Sudan", value: "Sudan" },
  // { label: "Suriname", value: "Suriname" },
  // { label: "Sweden", value: "Sweden" },
  // { label: "Switzerland", value: "Switzerland" },
  // { label: "Syria", value: "Syria" },
  // { label: "Taiwan", value: "Taiwan" },
  // { label: "Tajikistan", value: "Tajikistan" },
  // { label: "Tanzania", value: "Tanzania" },
  // { label: "Thailand", value: "Thailand" },
  // { label: "Timor-Leste", value: "Timor-Leste" },
  // { label: "Togo", value: "Togo" },
  // { label: "Tonga", value: "Tonga" },
  // { label: "Trinidad and Tobago", value: "Trinidad and Tobago" },
  // { label: "Tunisia", value: "Tunisia" },
  // { label: "Turkey", value: "Turkey" },
  // { label: "Turkmenistan", value: "Turkmenistan" },
  // { label: "Tuvalu", value: "Tuvalu" },
  // { label: "Uganda", value: "Uganda" },
  // { label: "Ukraine", value: "Ukraine" },
  // { label: "United Arab Emirates", value: "United Arab Emirates" },
  // { label: "United Kingdom", value: "United Kingdom" },
  // { label: "United States of America", value: "United States of America" },
  // { label: "Uruguay", value: "Uruguay" },
  // { label: "Uzbekistan", value: "Uzbekistan" },
  // { label: "Vanuatu", value: "Vanuatu" },
  // { label: "Venezuela", value: "Venezuela" },
  // { label: "Vietnam", value: "Vietnam" },
  // { label: "Yemen", value: "Yemen" },
  // { label: "Zambia", value: "Zambia" },
  // { label: "Zimbabwe", value: "Zimbabwe" },
];

export const statesByCountry: Record<
  string,
  { label: string; value: string }[]
> = {
  Nigeria: [
    { label: "Abia", value: "Abia" },
    { label: "Adamawa", value: "Adamawa" },
    { label: "Akwa Ibom", value: "Akwa Ibom" },
    { label: "Anambra", value: "Anambra" },
    { label: "Bauchi", value: "Bauchi" },
    { label: "Bayelsa", value: "Bayelsa" },
    { label: "Benue", value: "Benue" },
    { label: "Borno", value: "Borno" },
    { label: "Cross River", value: "Cross River" },
    { label: "Delta", value: "Delta" },
    { label: "Ebonyi", value: "Ebonyi" },
    { label: "Edo", value: "Edo" },
    { label: "Ekiti", value: "Ekiti" },
    { label: "Enugu", value: "Enugu" },
    { label: "Gombe", value: "Gombe" },
    { label: "Imo", value: "Imo" },
    { label: "Jigawa", value: "Jigawa" },
    { label: "Kaduna", value: "Kaduna" },
    { label: "Kano", value: "Kano" },
    { label: "Katsina", value: "Katsina" },
    { label: "Kebbi", value: "Kebbi" },
    { label: "Kogi", value: "Kogi" },
    { label: "Kwara", value: "Kwara" },
    { label: "Lagos", value: "Lagos" },
    { label: "Nasarawa", value: "Nasarawa" },
    { label: "Niger", value: "Niger" },
    { label: "Ogun", value: "Ogun" },
    { label: "Ondo", value: "Ondo" },
    { label: "Osun", value: "Osun" },
    { label: "Oyo", value: "Oyo" },
    { label: "Plateau", value: "Plateau" },
    { label: "Rivers", value: "Rivers" },
    { label: "Sokoto", value: "Sokoto" },
    { label: "Taraba", value: "Taraba" },
    { label: "Yobe", value: "Yobe" },
    { label: "Zamfara", value: "Zamfara" },
    { label: "Abuja (FCT)", value: "Abuja" },
  ],
};

export const colorsSelect = [
  { label: "AliceBlue", value: "aliceblue" },
  { label: "AntiqueWhite", value: "antiquewhite" },
  { label: "Aqua", value: "aqua" },
  { label: "Aquamarine", value: "aquamarine" },
  { label: "Azure", value: "azure" },
  { label: "Beige", value: "beige" },
  { label: "Bisque", value: "bisque" },
  { label: "Black", value: "black" },
  { label: "BlanchedAlmond", value: "blanchedalmond" },
  { label: "Blue", value: "blue" },
  { label: "BlueViolet", value: "blueviolet" },
  { label: "Brown", value: "brown" },
  { label: "BurlyWood", value: "burlywood" },
  { label: "CadetBlue", value: "cadetblue" },
  { label: "Chartreuse", value: "chartreuse" },
  { label: "Chocolate", value: "chocolate" },
  { label: "Coral", value: "coral" },
  { label: "CornflowerBlue", value: "cornflowerblue" },
  { label: "Cornsilk", value: "cornsilk" },
  { label: "Crimson", value: "crimson" },
  { label: "Cyan", value: "cyan" },
  { label: "DarkBlue", value: "darkblue" },
  { label: "DarkCyan", value: "darkcyan" },
  { label: "DarkGoldenRod", value: "darkgoldenrod" },
  { label: "DarkGray", value: "darkgray" },
  { label: "DarkGrey", value: "darkgrey" },
  { label: "DarkGreen", value: "darkgreen" },
  { label: "DarkKhaki", value: "darkkhaki" },
  { label: "DarkMagenta", value: "darkmagenta" },
  { label: "DarkOliveGreen", value: "darkolivegreen" },
  { label: "DarkOrange", value: "darkorange" },
  { label: "DarkOrchid", value: "darkorchid" },
  { label: "DarkRed", value: "darkred" },
  { label: "DarkSalmon", value: "darksalmon" },
  { label: "DarkSeaGreen", value: "darkseagreen" },
  { label: "DarkSlateBlue", value: "darkslateblue" },
  { label: "DarkSlateGray", value: "darkslategray" },
  { label: "DarkSlateGrey", value: "darkslategrey" },
  { label: "DarkTurquoise", value: "darkturquoise" },
  { label: "DarkViolet", value: "darkviolet" },
  { label: "DeepPink", value: "deeppink" },
  { label: "DeepSkyBlue", value: "deepskyblue" },
  { label: "DimGray", value: "dimgray" },
  { label: "DimGrey", value: "dimgrey" },
  { label: "DodgerBlue", value: "dodgerblue" },
  { label: "FireBrick", value: "firebrick" },
  { label: "FloralWhite", value: "floralwhite" },
  { label: "ForestGreen", value: "forestgreen" },
  { label: "Fuchsia", value: "fuchsia" },
  { label: "Gainsboro", value: "gainsboro" },
  { label: "GhostWhite", value: "ghostwhite" },
  { label: "Gold", value: "gold" },
  { label: "GoldenRod", value: "goldenrod" },
  { label: "Gray", value: "gray" },
  { label: "Grey", value: "grey" },
  { label: "Green", value: "green" },
  { label: "GreenYellow", value: "greenyellow" },
  { label: "HoneyDew", value: "honeydew" },
  { label: "HotPink", value: "hotpink" },
  { label: "IndianRed", value: "indianred" },
  { label: "Indigo", value: "indigo" },
  { label: "Ivory", value: "ivory" },
  { label: "Khaki", value: "khaki" },
  { label: "Lavender", value: "lavender" },
  { label: "LavenderBlush", value: "lavenderblush" },
  { label: "LawnGreen", value: "lawngreen" },
  { label: "LemonChiffon", value: "lemonchiffon" },
  { label: "LightBlue", value: "lightblue" },
  { label: "LightCoral", value: "lightcoral" },
  { label: "LightCyan", value: "lightcyan" },
  { label: "LightGoldenRodYellow", value: "lightgoldenrodyellow" },
  { label: "LightGray", value: "lightgray" },
  { label: "LightGrey", value: "lightgrey" },
  { label: "LightGreen", value: "lightgreen" },
  { label: "LightPink", value: "lightpink" },
  { label: "LightSalmon", value: "lightsalmon" },
  { label: "LightSeaGreen", value: "lightseagreen" },
  { label: "LightSkyBlue", value: "lightskyblue" },
  { label: "LightSlateGray", value: "lightslategray" },
  { label: "LightSlateGrey", value: "lightslategrey" },
  { label: "LightSteelBlue", value: "lightsteelblue" },
  { label: "LightYellow", value: "lightyellow" },
  { label: "Lime", value: "lime" },
  { label: "LimeGreen", value: "limegreen" },
  { label: "Linen", value: "linen" },
  { label: "Magenta", value: "magenta" },
  { label: "Maroon", value: "maroon" },
  { label: "MediumAquaMarine", value: "mediumaquamarine" },
  { label: "MediumBlue", value: "mediumblue" },
  { label: "MediumOrchid", value: "mediumorchid" },
  { label: "MediumPurple", value: "mediumpurple" },
  { label: "MediumSeaGreen", value: "mediumseagreen" },
  { label: "MediumSlateBlue", value: "mediumslateblue" },
  { label: "MediumSpringGreen", value: "mediumspringgreen" },
  { label: "MediumTurquoise", value: "mediumturquoise" },
  { label: "MediumVioletRed", value: "mediumvioletred" },
  { label: "MidnightBlue", value: "midnightblue" },
  { label: "MintCream", value: "mintcream" },
  { label: "MistyRose", value: "mistyrose" },
  { label: "Moccasin", value: "moccasin" },
  { label: "NavajoWhite", value: "navajowhite" },
  { label: "Navy", value: "navy" },
  { label: "OldLace", value: "oldlace" },
  { label: "Olive", value: "olive" },
  { label: "OliveDrab", value: "olivedrab" },
  { label: "Orange", value: "orange" },
  { label: "OrangeRed", value: "orangered" },
  { label: "Orchid", value: "orchid" },
  { label: "PaleGoldenRod", value: "palegoldenrod" },
  { label: "PaleGreen", value: "palegreen" },
  { label: "PaleTurquoise", value: "paleturquoise" },
  { label: "PaleVioletRed", value: "palevioletred" },
  { label: "PapayaWhip", value: "papayawhip" },
  { label: "PeachPuff", value: "peachpuff" },
  { label: "Peru", value: "peru" },
  { label: "Pink", value: "pink" },
  { label: "Plum", value: "plum" },
  { label: "PowderBlue", value: "powderblue" },
  { label: "Purple", value: "purple" },
  { label: "Red", value: "red" },
  { label: "RosyBrown", value: "rosybrown" },
  { label: "RoyalBlue", value: "royalblue" },
  { label: "SaddleBrown", value: "saddlebrown" },
  { label: "Salmon", value: "salmon" },
  { label: "SandyBrown", value: "sandybrown" },
  { label: "SeaGreen", value: "seagreen" },
  { label: "SeaShell", value: "seashell" },
  { label: "Sienna", value: "sienna" },
  { label: "Silver", value: "silver" },
  { label: "SkyBlue", value: "skyblue" },
  { label: "SlateBlue", value: "slateblue" },
  { label: "SlateGray", value: "slategray" },
  { label: "SlateGrey", value: "slategrey" },
  { label: "Snow", value: "snow" },
  { label: "SpringGreen", value: "springgreen" },
  { label: "SteelBlue", value: "steelblue" },
  { label: "Tan", value: "tan" },
  { label: "Teal", value: "teal" },
  { label: "Thistle", value: "thistle" },
  { label: "Tomato", value: "tomato" },
  { label: "Turquoise", value: "turquoise" },
  { label: "Violet", value: "violet" },
  { label: "Wheat", value: "wheat" },
  { label: "White", value: "white" },
  { label: "WhiteSmoke", value: "whitesmoke" },
  { label: "Yellow", value: "yellow" },
  { label: "YellowGreen", value: "yellowgreen" },
] as const;

export const genderSelect = [
  { label: "Men", value: "Men" },
  { label: "Ladies", value: "Ladies" },
  { label: "Kids", value: "Kids" },
] as const;

export const sizeOptionsMap = {
  euShoesSizes,
  usShoesSizes,
  ukShoesSizes,
  alphaClothingSizes,
  trouserSizes,
  kidsClothingSizes,
  capSizes,
  watchSizes,
  necklaceSizes,
  shirtNumberSizes,
  bagSizes,
} as const;

export type GenderValue = (typeof genderSelect)[number]["value"];
export type ColorValue = (typeof colorsSelect)[number]["value"];
export type SizeTypeKey = keyof typeof sizeOptionsMap;
